# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='role',
        ),
    ]
