# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_lease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='house_commission_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lease',
            name='house_salesrep_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='lease_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='outside_broker_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='rent_rate_factor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='asking_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='closing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='house_commission_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='house_rep_commission_split_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='outside_broker_commission_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
    ]
