# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_notice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
