# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0011_option_increase_or_decrease_rent_rate_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='increase_or_decrease_commission_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=5),
        ),
    ]
