# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0012_option_increase_or_decrease_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='option',
            name='option_contingencies',
            field=models.TextField(blank=True),
        ),
    ]
