# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0017_auto_20170111_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='option',
        ),
        migrations.AddField(
            model_name='option',
            name='lease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.Lease'),
        ),
    ]
