# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text='Enter the type of business', max_length=100)),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('tenant_name', models.CharField(blank=True, max_length=80)),
                ('property_owner_name', models.CharField(max_length=80)),
                ('status', models.CharField(blank=True, choices=[('0', 'New'), ('25', 'Prospect'), ('50', 'Signed LOI'), ('75', 'Signed Lease'), ('100', 'Closed')], default=0, help_text='Workflow status', max_length=3)),
                ('location_name', models.CharField(max_length=120)),
                ('signed_lease_date', models.DateField(blank=True, null=True)),
                ('lease_term_in_months', models.IntegerField(blank=True, null=True, verbose_name='lease term')),
                ('size_of_space', models.IntegerField(blank=True, default=0, null=True)),
                ('rent_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('lease_execution_date', models.DateField(blank=True, null=True)),
                ('contingency_start_date', models.DateField(blank=True, null=True)),
                ('contingency_end_date', models.DateField(blank=True, null=True)),
                ('rent_commencement_date', models.DateField(blank=True, null=True)),
                ('rent_rate_factor', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('occupancy_date', models.DateField(blank=True, null=True)),
                ('landlord_broker', models.CharField(blank=True, max_length=80)),
                ('tenant_broker', models.CharField(blank=True, max_length=80)),
                ('lease_expiration_date', models.DateField(blank=True, null=True)),
                ('contingencies', models.TextField(blank=True, max_length=1000)),
                ('deal_commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('house_broker', models.CharField(blank=True, max_length=80)),
                ('house_broker_commission_rate', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5, null=True)),
                ('outside_broker_commission_rate', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5, null=True)),
                ('commission_payout_terms', models.TextField(blank=True, max_length=1000)),
                ('send_invoice_to', models.CharField(blank=True, max_length=120)),
                ('invoice_address', models.CharField(blank=True, max_length=100)),
                ('invoice_city', models.CharField(blank=True, max_length=30)),
                ('invoice_state', models.CharField(blank=True, max_length=20)),
                ('invoice_zip', models.CharField(blank=True, max_length=12)),
                ('invoice_phone', models.CharField(blank=True, max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=80)),
                ('outside_broker_contact', models.CharField(blank=True, max_length=80)),
                ('outside_broker_contact_address', models.CharField(blank=True, max_length=100)),
                ('outside_broker_contact_phone_number', models.CharField(blank=True, max_length=15)),
                ('outside_broker_email_address', models.EmailField(blank=True, max_length=254)),
                ('outside_broker_w9_on_file', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('contingency_time_in_days', models.IntegerField(blank=True, default=0, null=True)),
                ('permit_type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name_of_property', models.CharField(max_length=120, verbose_name='property name')),
                ('property_owner', models.CharField(blank=True, max_length=80, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('availability', models.CharField(blank=True, choices=[('a', 'Available'), ('n', 'Not Available'), ('l', 'For Lease'), ('s', 'For Sale'), ('b', 'Sublet')], default='n', help_text='Location status', max_length=1)),
                ('property_type', models.CharField(blank=True, choices=[('nc', 'Not Classified'), ('p', 'Pad'), ('b', 'Bank'), ('l', 'Land')], default='nc', max_length=2)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('min_size', models.PositiveIntegerField(blank=True, null=True)),
                ('max_size', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_square_foot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField(blank=True)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('contingencies', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.Lease')),
            ],
            options={
                'ordering': ('-expiration_date',),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('buyer_name', models.CharField(blank=True, max_length=80)),
                ('seller_name', models.CharField(blank=True, max_length=80)),
                ('location_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, choices=[('0', 'New'), ('25', 'Prospect'), ('50', 'Signed LOI'), ('75', 'Signed Contract'), ('100', 'Closed')], default=0, help_text='Workflow status', max_length=3)),
                ('transaction_close_date', models.DateField(blank=True, null=True, verbose_name='close date')),
                ('asking_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('contract_execution_date', models.DateField(blank=True, null=True, verbose_name='contract signed on')),
                ('sellers_broker', models.CharField(blank=True, max_length=80)),
                ('buyers_broker', models.CharField(blank=True, max_length=80)),
                ('house_broker', models.CharField(blank=True, max_length=80)),
                ('contingencies', models.TextField(blank=True, max_length=1000)),
                ('closing_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('deal_commission_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('house_rep_commission_split_rate', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('outside_broker_commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('commission_due_date', models.DateField(blank=True, null=True, verbose_name='commission paid on')),
                ('commission_payout_terms', models.TextField(blank=True, max_length=1000)),
                ('send_invoice_to', models.CharField(blank=True, max_length=120)),
                ('invoice_address', models.CharField(blank=True, max_length=100)),
                ('invoice_phone', models.CharField(blank=True, max_length=15)),
                ('invoice_city', models.CharField(blank=True, max_length=30)),
                ('invoice_state', models.CharField(blank=True, max_length=20)),
                ('invoice_zip', models.CharField(blank=True, max_length=12)),
                ('contact_person', models.CharField(blank=True, max_length=80)),
                ('outside_broker_contact', models.CharField(blank=True, max_length=80)),
                ('outside_broker_contact_address', models.CharField(blank=True, max_length=100)),
                ('outside_broker_contact_phone_number', models.CharField(blank=True, max_length=15)),
                ('outside_broker_email_address', models.EmailField(blank=True, max_length=254)),
                ('outside_broker_w9_on_file', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name_of_company', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('locations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.Location')),
            ],
            options={
                'ordering': ('name_of_company',),
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('terms', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('lease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.Lease')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='tenants',
            field=models.ManyToManyField(blank=True, to='commissions.Tenant'),
        ),
    ]
