# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(blank=True, max_length=80)),
                ('property_owner_name', models.CharField(max_length=80)),
                ('location_name', models.CharField(max_length=120)),
                ('signed_lease_date', models.DateField(blank=True, null=True)),
                ('lease_term_in_months', models.IntegerField(blank=True, null=True, verbose_name='lease term')),
                ('size_of_transaction', models.IntegerField(blank=True, default=0, null=True)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contract_execution_date', models.DateField(blank=True, null=True)),
                ('free_rent_start_date', models.DateField(blank=True, null=True)),
                ('free_rent_end_date', models.DateField(blank=True, null=True)),
                ('due_diligence_start_date', models.DateField(blank=True, null=True)),
                ('due_diligence_end_date', models.DateField(blank=True, null=True)),
                ('rent_commencement_date', models.DateField(blank=True, null=True)),
                ('rent_rate_factor', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('occupancy_date', models.DateField(blank=True, null=True)),
                ('landlord', models.CharField(blank=True, max_length=80)),
                ('tenant_broker', models.CharField(blank=True, max_length=80)),
                ('lease_expiration_date', models.DateField(blank=True, null=True)),
                ('contingencies', models.TextField(blank=True, max_length=1000)),
                ('deal_commission_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('house_salesrep_commission_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('outside_broker_commission_rate', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5, null=True)),
                ('commission_payout_terms', models.TextField(blank=True, max_length=1000)),
                ('send_invoice_to', models.CharField(blank=True, max_length=120)),
                ('invoice_address', models.CharField(blank=True, max_length=100)),
                ('invoice_city', models.CharField(blank=True, max_length=30)),
                ('invoice_state', models.CharField(blank=True, max_length=20)),
                ('invoice_zip', models.CharField(blank=True, max_length=12)),
                ('invoice_phone', models.CharField(blank=True, max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=80)),
                ('outside_broker_contact', models.CharField(blank=True, max_length=80)),
                ('outside_broker_contact_address', models.CharField(blank=True, max_length=100)),
                ('outside_broker_contact_phone_number', models.CharField(blank=True, max_length=15)),
                ('outside_broker_email_address', models.EmailField(blank=True, max_length=254)),
                ('outside_broker_w9_on_file', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_terms', models.TextField(blank=True)),
                ('option_notice_date', models.DateField(blank=True, null=True)),
                ('option_commencement_date', models.DateField(blank=True, null=True)),
                ('option_expiration_date', models.DateField(blank=True, null=True)),
                ('increase_or_decrease_size', models.IntegerField(blank=True, null=True)),
                ('increase_or_decrease_rent_rate_factor', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('option_contingencies', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.Lease')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=80)),
                ('seller_name', models.CharField(blank=True, max_length=80)),
                ('location_name', models.CharField(blank=True, max_length=120)),
                ('transaction_close_date', models.DateField(blank=True, null=True, verbose_name='close date')),
                ('asking_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('contract_execution_date', models.DateField(blank=True, null=True, verbose_name='contract signed on')),
                ('sellers_broker', models.CharField(blank=True, max_length=80)),
                ('buyers_broker', models.CharField(blank=True, max_length=80)),
                ('contingencies', models.TextField(blank=True, max_length=1000)),
                ('closing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('deal_commission_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('house_rep_commission_split_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('outside_broker_commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('commission_due_date', models.DateField(blank=True, null=True, verbose_name='commission paid on')),
                ('commission_payout_terms', models.TextField(blank=True, max_length=1000)),
                ('send_invoice_to', models.CharField(blank=True, max_length=120)),
                ('invoice_address', models.CharField(blank=True, max_length=100)),
                ('invoice_phone', models.CharField(blank=True, max_length=15)),
                ('invoice_city', models.CharField(blank=True, max_length=30)),
                ('invoice_state', models.CharField(blank=True, max_length=20)),
                ('invoice_zip', models.CharField(blank=True, max_length=12)),
                ('contact_person', models.CharField(blank=True, max_length=80)),
                ('outside_broker_contact', models.CharField(blank=True, max_length=80)),
                ('outside_broker_contact_address', models.CharField(blank=True, max_length=100)),
                ('outside_broker_contact_phone_number', models.CharField(blank=True, max_length=15)),
                ('outside_broker_email_address', models.EmailField(blank=True, max_length=254)),
                ('outside_broker_w9_on_file', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
            options={
                'ordering': ['location_name'],
            },
        ),
    ]
