# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='size_of_transaction',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
