# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='contract_execution_date',
            new_name='contingency_end_date',
        ),
        migrations.RenameField(
            model_name='lease',
            old_name='due_diligence_end_date',
            new_name='contingency_start_date',
        ),
        migrations.RenameField(
            model_name='lease',
            old_name='landlord',
            new_name='landlord_broker',
        ),
        migrations.RenameField(
            model_name='lease',
            old_name='due_diligence_start_date',
            new_name='lease_execution_date',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='free_rent_end_date',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='free_rent_start_date',
        ),
        migrations.AddField(
            model_name='sale',
            name='house_broker',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='lease',
            name='deal_commission_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lease',
            name='house_salesrep_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='option',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='option',
            name='increase_or_decrease_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='closing_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
