# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(blank=True, max_length=80)),
                ('property_owner_name', models.CharField(max_length=80)),
                ('location_name', models.CharField(max_length=120)),
                ('signed_lease_date', models.DateField(blank=True, null=True)),
                ('lease_term_in_months', models.IntegerField(blank=True, null=True, verbose_name='lease term')),
                ('size_of_transaction', models.IntegerField(blank=True, null=True)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('free_rent_start_date', models.DateField(blank=True, null=True)),
                ('free_rent_end_date', models.DateField(blank=True, null=True)),
                ('due_diligence_rent_start_date', models.DateField(blank=True, null=True)),
                ('due_diligence_end_date', models.DateField(blank=True, null=True)),
                ('contract_execution_date', models.DateField(blank=True, null=True)),
                ('rent_commencement_date', models.DateField(blank=True, null=True)),
                ('rent_rate_factor', models.DecimalField(decimal_places=4, default=1, max_digits=4)),
                ('occupancy_date', models.DateField(blank=True, null=True)),
                ('landlord', models.CharField(blank=True, max_length=80)),
                ('tenant_broker', models.CharField(blank=True, max_length=80)),
                ('lease_expiration_date', models.DateField(blank=True)),
                ('contingencies', models.TextField(blank=True, max_length=1000)),
                ('house_commission_rate', models.DecimalField(decimal_places=3, default=1.0, max_digits=4)),
                ('house_salesrep_commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('outside_broker_commission_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('commission_payout_terms', models.TextField(blank=True, max_length=1000)),
                ('send_invoice_to', models.CharField(blank=True, max_length=120)),
                ('invoice_address', models.CharField(blank=True, max_length=100)),
                ('invoice_city', models.CharField(blank=True, max_length=30)),
                ('invoice_state', models.CharField(blank=True, max_length=20)),
                ('invoice_zip', models.CharField(blank=True, max_length=12)),
                ('invoice_phone', models.CharField(blank=True, max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=80)),
                ('outside_broker_contact', models.CharField(blank=True, max_length=80)),
                ('outside_broker_contact_address', models.CharField(blank=True, max_length=100)),
                ('outside_broker_contact_phone_number', models.CharField(blank=True, max_length=15)),
                ('outside_broker_email_address', models.EmailField(blank=True, max_length=254)),
                ('outside_broker_w9_on_file', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
    ]
