# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commissions', '0002_auto_20170121_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name_of_company', models.CharField(blank=True, max_length=80)),
                ('is_a_tenant_rep', models.BooleanField(default=True)),
                ('contact', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('business_type_tags', models.ManyToManyField(help_text='Select the types of businesses that represent the tenant', to='commissions.BusinessType')),
            ],
            options={
                'verbose_name': 'tenant rep',
                'ordering': ('name_of_company',),
                'verbose_name_plural': 'tenant reps',
            },
        ),
        migrations.RemoveField(
            model_name='tenantrep',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='tenantrep',
            name='business_type_tags',
        ),
        migrations.RemoveField(
            model_name='tenantrep',
            name='locations',
        ),
        migrations.AlterField(
            model_name='location',
            name='tenants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.Tenant'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.Tenant'),
        ),
        migrations.DeleteModel(
            name='TenantRep',
        ),
        migrations.AddField(
            model_name='tenant',
            name='locations',
            field=models.ManyToManyField(blank=True, to='commissions.Location'),
        ),
    ]
