# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_auto_20170128_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='contingency_end_date',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='permit_type',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='signed_lease_date',
        ),
        migrations.AddField(
            model_name='lease',
            name='contingency_period_in_days',
            field=models.IntegerField(default=0, verbose_name='contingency period'),
        ),
    ]
