# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_auto_20170113_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_terms', models.TextField(blank=True)),
                ('term_start_date', models.DateField(blank=True, null=True)),
                ('term_end_date', models.DateField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_owner_name', models.CharField(max_length=80)),
                ('location_name', models.CharField(blank=True, max_length=120, null=True)),
                ('location_address', models.CharField(blank=True, max_length=120, null=True)),
                ('term_of_agreement', models.IntegerField(blank=True, default=0, null=True)),
                ('invoice_contact_name', models.CharField(blank=True, max_length=120, null=True)),
                ('invoice_billing_address', models.CharField(blank=True, max_length=120, null=True)),
                ('invoice_billing_city', models.CharField(blank=True, max_length=30, null=True)),
                ('invoice_billing_state', models.CharField(blank=True, max_length=30, null=True)),
                ('invoice_billing_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('listing_exectution_date', models.DateField(blank=True, null=True)),
                ('listing_expiration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', help_text='Listing status', max_length=25)),
                ('listing_type', models.CharField(blank=True, choices=[('not_classified', 'Not Classified'), ('pad', 'Pad'), ('space', 'Space')], default='not_classified', help_text='Property type', max_length=25)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lease',
            name='size_of_transaction',
        ),
        migrations.AddField(
            model_name='lease',
            name='contingency_time_in_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='permit_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lease',
            name='size_of_space',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaseterms',
            name='lease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.Lease'),
        ),
    ]
