# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_auto_20170129_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='contingency_time_in_days',
        ),
    ]
