# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_auto_20170121_0430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ('name_of_company',)},
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='locations',
        ),
        migrations.AddField(
            model_name='tenant',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.Location'),
        ),
    ]
