# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_auto_20170111_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='due_diligence_tart_date',
            new_name='due_diligence_start_date',
        ),
    ]
