# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('commissions', '0004_auto_20170121_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='business_type_tags',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_a_tenant_rep',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='locations',
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='tenants',
        ),
        migrations.AddField(
            model_name='location',
            name='tenants',
            field=models.ManyToManyField(blank=True, null=True, to='commissions.Tenant'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='price_per_square_foot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
