# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_auto_20170121_0529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mandate',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='location',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='tags',
        ),
        migrations.AlterField(
            model_name='location',
            name='tenants',
            field=models.ManyToManyField(blank=True, to='commissions.Tenant'),
        ),
    ]
