# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0009_option_option_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='increase_or_decrease_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
