# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0010_auto_20170122_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='location',
            name='term_of_agreement',
        ),
    ]
