# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0011_auto_20170122_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='tags',
        ),
        migrations.AlterField(
            model_name='location',
            name='name_of_property',
            field=models.CharField(max_length=120, verbose_name='property name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='tenants',
            field=models.ManyToManyField(blank=True, null=True, to='commissions.Tenant'),
        ),
    ]
