# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0012_auto_20170122_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='contact',
        ),
        migrations.AlterField(
            model_name='location',
            name='tenants',
            field=models.ManyToManyField(blank=True, to='commissions.Tenant'),
        ),
    ]
