# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0013_auto_20170122_0540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaseoption',
            options={'ordering': ('-expiration_date',), 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
    ]
