# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0014_auto_20170111_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='increase_or_decrease_commission_rate',
            new_name='commission_rate',
        ),
    ]
