# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0015_auto_20170122_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='term_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='term_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='option_terms',
            new_name='terms',
        ),
    ]
