# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0016_auto_20170123_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'New'), ('25', 'Prospect'), ('50', 'Signed LOI'), ('75', 'Signed Lease'), ('100', 'Closed')], default='0', help_text='Workflow status', max_length=1),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'New'), ('25', 'Prospect'), ('50', 'Signed LOI'), ('75', 'Signed Contract'), ('100', 'Closed')], default='0', help_text='Workflow status', max_length=1),
        ),
    ]
